'\" tbl
.TH "mesg" "1" "03 Марта 2019" "mesg version 1.0" "mesg" 
.
.
.SH "NAME"
 MESG - рарешение или запрет сообщений 
.PP
mesg  [n] [y]
.
.SH "DESCRIPTION"

.TS
center, box, tab(:);
cs
l|l
l | l.
Описание доступных атрибутов
=
ТИП АТРИБУТА:ЗНАЧЕНИЕ АТРИБУТА
=

Доступность:SUNWlpr-cmds
=

Стильность Интерфейса:Standard
.TE



.PP
Команда mesg с аргументом n, лишая права записи в терминальный файл всех, кроме владельца, запрещает посылать сообщения на терминал пользователя посредством команды write(1).
.PP
Команда mesg с аргументом y восстанавливает право посылки сообщений. Mesg без аргументов сообщает о состоянии терминала (is y - посылка разрешена, is n - запрещена), не меняя состояние.
.SH "OPTIONS"

- n Запрещает другим пользователям посылать на терминал сообщения, смотри команду write(1)
.PP
- y Дает право другим пользователям посылать на терминал сообщения
.SH "ENVIRONMENT" 
LANG определяет языковую настройку сессии.
.PP 
LC_ALL контролирует локализацию некоторых программ, делает вывод их сообщений зависимым от страны.
.PP 
LC_CTYPE Определяет локаль для обработки байтов текстовых данных как символов (однобайтовых или многобайтовых), а также для проверки того, является ли данный символ буквой (класс алфавитных символов - alpha), и выбора символов по шаблону.
.PP
LC_MESSAGES Задает язык, на котором выдаются сообщения.
.SH "EXIT STATUS"
0 - Посылка сообщений разрешена.
.PP 
1 - Посылка сообщений запрещена.
.PP 
2 - Зафиксированы ошибки.
.PP

.SH "EXAMPLE" 
mesg y  позволяет другим пользователям посылать тебе сообщения
.PP
mesg n  запрещает посылать сообщения
.PP
mesg выводит информацию о текущем статусе разрешения
.SH "FILES"
/dev/tty*
.

.SH "AUTHOR"
Сделано с любовью, Р3211 Симаненко Юлия
. /usr/local/etc/profile
